import styles from './page.module.css'

export const metadata = {
  title: 'About',
  description: 'About Me Generated by create next app',
}
const About = () => {
  return (
    <div>
      <h1 className={styles.title}>About Page</h1>
    </div>
  )
}

export default About
