import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})
export const metadata = {
  title: {
    default: 'Next.JS', // اگر صفحه‌ای تایتل نداشت این نشان داده می‌شود
    template: 'Next.JS | %s', // %s با تایتل هر صفحه جایگزین می‌شود
  },
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
