import { H1 } from '@/components/Typography'
import { css } from '../../../styled-system/css'
export const metadata = {
  title: 'Blog',
  description: 'About Me Generated by create next app',
}

const Blog = (props) => {
  console.log('params: ', props)
  return (
    <div>
      <H1>Blog Page</H1>
      <div
        className={css({
          bg: 'bg',
          color: 'text',
          fontFamily: 'body',
          fontSize: 'lg',
          p: '3',
          rounded: 'card',
        })}
      >
        Hello Panda + Next.js Font
      </div>
    </div>
  )
}

export default Blog
