export const metadata = {
  title: 'Blog',
  description: 'About Me Generated by create next app',
}
const Blog = (props) => {
  console.log('params: ', props)
  return (
    <div>
      <h1>Blog Page</h1>
    </div>
  )
}

export default Blog
